version: "3.7"
services:

  telegrambot:
    build:
      dockerfile: build/telegrambot/Dockerfile
      context: .
    restart: always
    container_name: telegrambot
    env_file: build/telegrambot/cfg.env
    depends_on:
      - database

  database:
    image: postgres:11
    restart: always
    container_name: postgres
    env_file: build/postgres/cfg.env
    volumes:
      - ./build/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
