// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package box

import (
	"Instracker/internal/config"
	"Instracker/internal/database"
	"Instracker/internal/instagram"
	"Instracker/internal/telegrambotapi"
)

// Injectors from wire.go:

func InitializeBox(configPath string) (*Box, error) {
	configConfig, err := config.NewConfig(configPath)
	if err != nil {
		return nil, err
	}
	databaseDatabase, err := database.NewDatabase(configConfig)
	if err != nil {
		return nil, err
	}
	instagramInstagram, err := instagram.NewInstagram(configConfig)
	if err != nil {
		return nil, err
	}
	telegramBotAPI, err := telegrambotapi.NewTelegramBotAPI(configConfig)
	if err != nil {
		return nil, err
	}
	box := NewBox(configConfig, databaseDatabase, instagramInstagram, telegramBotAPI)
	return box, nil
}
